### ISSUE TITLE
Websocket Server: api no longer working

### ISSUE THREAD

**Issue by nkostoulas** [commerceblock/mainstay-mvc#44]
@Vardan-Alaverdyan reported this

Using `npm install` i get the following

```
$ sudo DB_USER=apiUser DB_PASSWORD=apiPass DB_NAME=mainstayX DB_PORT=27017 DB_HOST=127.0.0.1 LISTEN_API=4000 node ./src/app.js
/Users/nikolaos/commerceblock/mainstay-view/node_modules/mongodb/lib/utils.js:132
      throw err;
      ^

Error: The $changeStream stage is only supported on replica sets
    at queryCallback (/Users/nikolaos/commerceblock/mainstay-view/node_modules/mongodb-core/lib/cursor.js:248:25)
    at /Users/nikolaos/commerceblock/mainstay-view/node_modules/mongodb-core/lib/connection/pool.js:532:18
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

No longer possible to run api.

Solution for now: 
`git checkout` 4ee4a4feff9c4d9979628f5d5926065ea373387b

**Comment by lodenos** [comment]
Use command $ Yarn , node install it's chit

**Comment by lodenos** [comment]
It's running if u follow new process write in README.md
