### ISSUE TITLE
API: App crashes when Latest Attestation data changes

### ISSUE THREAD

**Issue by nkostoulas** [commerceblock/mainstay-mvc#46]
**When a single field changes (i.e. `inserted_at`, web socket server and thus whole application crashes. This happens when attestation goes from unconfirmed to confirmed or when attestation date is updated.**

- Websocket server crash
```
TypeError: Cannot read property 'merkle_root' of undefined
    at ChangeStream.streamAttestation.on (/Users/nikolaos/commerceblock/mainstay-view/src/websocket/mainstay_websocket.js:247:25)
    at ChangeStream.emit (events.js:189:13)
    at ChangeStream.driverChangeStream.on.data (/Users/nikolaos/commerceblock/mainstay-view/node_modules/mongoose/lib/cursor/ChangeStream.js:38:51)
    at ChangeStream.emit (events.js:189:13)
    at processNewChange (/Users/nikolaos/commerceblock/mainstay-view/node_modules/mongodb/lib/change_stream.js:443:41)
    at Cursor.cursor.on.change (/Users/nikolaos/commerceblock/mainstay-view/node_modules/mongodb/lib/change_stream.js:93:11)
    at Cursor.emit (events.js:189:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Cursor.Readable.push (_stream_readable.js:224:10)
    at next (/Users/nikolaos/commerceblock/mainstay-view/node_modules/mongodb/lib/cursor.js:1037:10)
    at result (/Users/nikolaos/commerceblock/mainstay-view/node_modules/mongodb/lib/utils.js:414:17)
    at executeCallback (/Users/nikolaos/commerceblock/mainstay-view/node_modules/mongodb/lib/utils.js:406:9)
    at handleCallback (/Users/nikolaos/commerceblock/mainstay-view/node_modules/mongodb/lib/utils.js:128:55)
    at cursor._next (/Users/nikolaos/commerceblock/mainstay-view/node_modules/mongodb/lib/operations/cursor_ops.js:187:5)
    at handleCallback (/Users/nikolaos/commerceblock/mainstay-view/node_modules/mongodb-core/lib/cursor.js:203:5)
```

- data in line 245 @ main_websocket.js
```
{ _id:
   { _data:
      Binary {
        _bsontype: 'Binary',
        sub_type: 0,
        position: 49,
        buffer:
         <Buffer 82 5c 0f b2 d3 00 00 00 01 46 64 5f 69 64 00 64 5c 0f aa 2d e9 65 ad 60 5b e1 96 7b 00 5a 10 04 12 8b 61 af e9 53 47 55 95 89 29 e1 fc 3f 08 de 04> } },
  operationType: 'update',
  clusterTime:
   Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1544532691 },
  ns: { db: 'mainstay1', coll: 'Attestation' },
  documentKey: { _id: 5c0faa2de965ad605be1967b },
  updateDescription:
   { updatedFields: { inserted_at: 2018-12-11T12:51:31.141Z },
     removedFields: [] } }
```

**Comment by nkostoulas** [comment]
Also crash when db is empty

**Comment by lodenos** [comment]
The problem is not existing maybe the version where it was, and corrected because it did not have to finish
