### ISSUE TITLE
API: Invalid requests crashing API and incomplete post request API

### ISSUE THREAD

**Issue by nkostoulas** [commerceblock/mainstay-mvc#74]
<Buffer 7b 22 63 6f 6d 6d 69 74 6d 65 6e 74 22 3a 20 22 31 61 33 39 65 33 34 65 38 38 31 64 39 61 31 65 36 63 64 63 33 34 31 38 62 35 34 61 61 35 37 37 34 37 ... 66 more bytes>
{ commitment:
   '1a39e34e881d9a1e6cdc3418b54aa57747106bc75e9e84426661f27f98ada3b7',
  position: -1,
  token: 'dummy' }
/Users/nikolaos/commerceblock/mainstay-view/node_modules/nodejs-base64/index.js:29
    throw new Error('Input value must be a string.');
    ^

Error: Input value must be a string.
    at base64decode (/Users/nikolaos/commerceblock/mainstay-view/node_modules/nodejs-base64/index.js:29:11)
    at IncomingMessage.req.on.chunk (/Users/nikolaos/commerceblock/mainstay-view/src/controllers/controllers.js:461:32)
    at IncomingMessage.emit (events.js:189:13)
    at IncomingMessage.Readable.read (_stream_readable.js:491:10)
    at flow (_stream_readable.js:935:34)
    at resume_ (_stream_readable.js:916:3)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)

**Comment by nkostoulas** [comment]
No error catching at all

**Comment by nkostoulas** [comment]
Single POST request would crash our API...

**Comment by nkostoulas** [comment]
POST requests still using bitcore
